name: Cervino
on: push
jobs:
  binaries:
    name: Binaries
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - operating-system: ubuntu-latest
            ocaml-version: 4.11.0
            artifact-name: cervino-linux-x86_64
          - operating-system: macos-latest
            ocaml-version: 4.11.0
            artifact-name: cervino-macos-x86_64
          - operating-system: windows-latest
            ocaml-version: 4.11.0
            artifact-name: cervino-win32-x86_64
    steps:
    - uses: actions/checkout@master
    - uses: avsm/setup-ocaml@v1
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - run: opam pin add cervino -n .
    - name: Packages
      run: opam depext -yt cervino
    - name: Dependencies
      run: opam install -t . --deps-only 
    - name: Build
      run: opam exec -- dune build @install
    - uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.artifact-name }}
        path: cervino.exe
